// Role → sidebar items, moved out of sidebar.tsx so plain-TS logic and tests can read them.
// The item set per role is golden data: lib/__tests__/sidebar-groups.test.ts pins it to main.
import {
  LayoutDashboard,
  ShoppingCart,
  Building2,
  Warehouse,
  CreditCard,
  Users,
  TrendingUp,
  DollarSign,
  Package,
  UsersIcon,
  Wallet,
  Sparkles,
  TrendingUpIcon,
  Settings,
  BarChart3,
  Calculator,
  PackageX,
  ClipboardCheck,
  CheckSquare,
  Activity,
  FileText,
  Truck,
  UserCog,
  ArrowLeftRight,
  Wrench,
  type LucideIcon,
} from "lucide-react"
import type { UserRole } from "@/lib/types"

export interface NavItem {
  id: string
  label: string
  icon: LucideIcon
}

export const ROLE_MODULES: Record<UserRole, NavItem[]> = {
  admin: [
    { id: "user-management", label: "module.user-management", icon: UsersIcon },
    { id: "hr-management", label: "module.hr-management", icon: UserCog },
    { id: "metrics-validation", label: "module.metrics-validation", icon: CheckSquare },
    { id: "system-health", label: "module.system-health", icon: Activity },
  ],
  ceo: [
    { id: "dashboard", label: "module.dashboard", icon: LayoutDashboard },
    { id: "analytics", label: "module.analytics", icon: BarChart3 },
    { id: "ceo-chat", label: "module.ceo-chat", icon: Sparkles },
    { id: "hr-management", label: "module.hr-management", icon: UserCog },
    { id: "suppliers", label: "module.suppliers", icon: Building2 },
    { id: "products", label: "module.products", icon: Package },
    { id: "po-requests", label: "module.po-requests", icon: FileText },
    { id: "purchase-orders", label: "module.purchase-orders", icon: ShoppingCart },
    { id: "pricing-review", label: "module.pricing-review", icon: TrendingUpIcon },
    { id: "costing-settings", label: "module.costing-settings", icon: Settings },
    { id: "inventory", label: "module.inventory", icon: Warehouse },
    { id: "inventory-audit", label: "module.inventory-audit", icon: ClipboardCheck },
    { id: "goods-receipt-tracking", label: "module.goods-receipt-tracking", icon: ClipboardCheck },
    { id: "reorder-suggestions", label: "module.reorder-suggestions", icon: Calculator },
    { id: "lost-sales", label: "module.lost-sales", icon: PackageX },
    { id: "accounts-payable", label: "module.accounts-payable", icon: CreditCard },
    { id: "customers", label: "module.customers", icon: Users },
    { id: "sales-orders", label: "module.sales-orders", icon: TrendingUp },
    { id: "delivery-permits", label: "module.delivery-permits", icon: FileText },
    { id: "accounts-receivable", label: "module.accounts-receivable", icon: DollarSign },
    { id: "balance", label: "module.balance", icon: Wallet },
    { id: "metrics-validation", label: "module.metrics-validation", icon: CheckSquare },
    { id: "system-health", label: "module.system-health", icon: Activity },
  ],
  accountant: [
    { id: "dashboard", label: "module.dashboard", icon: LayoutDashboard },
    { id: "analytics", label: "module.analytics", icon: BarChart3 },
    { id: "approve-sales-orders", label: "module.approve-sales-orders", icon: CheckSquare },
    { id: "sales-quotations", label: "module.sales-quotations", icon: FileText },
    { id: "payment-schedule", label: "module.payment-schedule", icon: DollarSign },
    { id: "purchase-orders", label: "module.purchase-orders", icon: ShoppingCart },
    { id: "pricing-review", label: "module.pricing-review", icon: TrendingUpIcon },
    { id: "costing-settings", label: "module.costing-settings", icon: Settings },
    { id: "accounts-payable", label: "module.accounts-payable", icon: CreditCard },
    { id: "accounts-receivable", label: "module.accounts-receivable", icon: DollarSign },
    { id: "maintenance-invoices", label: "module.maintenance-invoices", icon: Wrench },
    { id: "customers", label: "module.customers", icon: Users },
    { id: "suppliers", label: "module.suppliers", icon: Building2 },
    { id: "delivery-permits", label: "module.delivery-permits", icon: FileText },
    { id: "balance", label: "module.balance", icon: Wallet },
  ],
  "sales-rep": [
    { id: "dashboard", label: "module.dashboard", icon: LayoutDashboard },
    { id: "analytics", label: "module.analytics", icon: BarChart3 },
    { id: "customers", label: "module.customers", icon: Users },
    { id: "sales-orders", label: "module.sales-orders", icon: TrendingUp },
    { id: "delivery-permits", label: "module.delivery-permits", icon: FileText },
    { id: "inventory", label: "module.inventory", icon: Warehouse },
    { id: "lost-sales", label: "module.lost-sales", icon: PackageX },
    { id: "accounts-receivable", label: "module.accounts-receivable", icon: DollarSign },
    { id: "operations-management", label: "module.operations-management", icon: Wrench },
  ],
  "warehouse-rep": [
    { id: "dashboard", label: "module.dashboard", icon: LayoutDashboard },
    { id: "inventory", label: "module.inventory", icon: Warehouse },
    { id: "inventory-audit", label: "module.inventory-audit", icon: ClipboardCheck },
    { id: "warehouse-transfers", label: "module.warehouse-transfers", icon: ArrowLeftRight },
    { id: "warehouse-delivery", label: "module.warehouse-delivery", icon: Package },
    { id: "delivery-permits", label: "module.delivery-permits", icon: FileText },
    { id: "goods-receipt", label: "module.goods-receipt", icon: Package },
    { id: "goods-receipt-tracking", label: "module.goods-receipt-tracking", icon: ClipboardCheck },
  ],
  "po-rep": [
    { id: "dashboard", label: "module.dashboard", icon: LayoutDashboard },
    { id: "analytics", label: "module.analytics", icon: BarChart3 },
    { id: "suppliers", label: "module.suppliers", icon: Building2 },
    { id: "products", label: "module.products", icon: Package },
    { id: "po-requests", label: "module.po-requests", icon: FileText },
    { id: "purchase-orders", label: "module.purchase-orders", icon: ShoppingCart },
    { id: "goods-receipt-tracking", label: "module.goods-receipt-tracking", icon: ClipboardCheck },
    { id: "inventory", label: "module.inventory", icon: Warehouse },
    { id: "reorder-suggestions", label: "module.reorder-suggestions", icon: Calculator },
    { id: "lost-sales", label: "module.lost-sales", icon: PackageX },
  ],
  shipment: [
    { id: "shipment", label: "module.shipping", icon: Truck },
    { id: "courier-management", label: "module.courier-management", icon: UserCog },
    { id: "delivery-permits", label: "module.delivery-permits", icon: FileText },
    { id: "operations-management", label: "module.operations-management", icon: Users },
  ],
}

export const ROLE_DISPLAY_NAMES: Record<UserRole, string> = {
  admin: "role.admin",
  ceo: "role.ceo",
  accountant: "role.accountant",
  "sales-rep": "role.sales-rep",
  "warehouse-rep": "role.warehouse-rep",
  "po-rep": "role.purchasing",
  shipment: "role.shipping",
}
